version: "3.3"

services:
  nginx:
    build:
      context: .
      dockerfile: docker/Nginx.Dockerfile
    ports:
      - 80:8080
    links:
      - fpm
    volumes:
      - ./:/var/www/steering_api
  fpm:
    build:
      context: .
      dockerfile: docker/Fpm.Dockerfile
    volumes:
      - ./:/var/www/steering_api
    links:
      - mysql
    environment:
      XDEBUG_CONFIG: "remote_host=127.0.0.1 remote_enable=1 remote_autostart=off  remote_port=9009"
      PHP_IDE_CONFIG: "serverName=two"
  mysql:
    image: mysql:8
    ports:
      - 33061:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=laravel
